[target.'cfg(all())']
rustflags = [
	# Deny `unsafe`.
	"-Dunsafe_code",
	# Clippy groups.
	"-Wclippy::all",
	"-Wclippy::cargo",
	"-Wclippy::nursery",
	"-Wclippy::pedantic",
	# Allowed Clippy lints.
	"-Aclippy::module_name_repetitions",
	"-Aclippy::redundant_pub_crate",
	# Clippy restriction lints.
	"-Wclippy::as_conversions",
	"-Wclippy::clone_on_ref_ptr",
	"-Wclippy::default_numeric_fallback",
	"-Wclippy::empty_structs_with_brackets",
	"-Wclippy::if_then_some_else_none",
	"-Wclippy::lossy_float_literal",
	"-Wclippy::missing_docs_in_private_items",
	"-Wclippy::rest_pat_in_fully_bound_structs",
	"-Wclippy::same_name_method",
	"-Wclippy::single_char_lifetime_names",
	"-Wclippy::str_to_string",
	"-Wclippy::string_add",
	"-Wclippy::string_slice",
	"-Wclippy::string_to_string",
	"-Wclippy::try_err",
	"-Wclippy::undocumented_unsafe_blocks",
	"-Wclippy::unnecessary_self_imports",
	"-Wclippy::unneeded_field_pattern",
	"-Wclippy::unseparated_literal_suffix",
	"-Wclippy::unwrap_used",
	# Rustdoc group.
	"-Wrustdoc::all",
	# Rust groups.
	"-Wfuture_incompatible",
	"-Wnonstandard_style",
	"-Wrust_2018_compatibility",
	"-Wrust_2018_idioms",
	"-Wrust_2021_compatibility",
	"-Wunused",
	# Rust lints.
	"-Wdeprecated_in_future",
	"-Wmacro_use_extern_crate",
	"-Wmeta_variable_misuse",
	"-Wmissing_abi",
	"-Wmissing_copy_implementations",
	"-Wmissing_debug_implementations",
	"-Wmissing_docs",
	"-Wnon_ascii_idents",
	"-Wnoop_method_call",
	"-Wsingle_use_lifetimes",
	"-Wtrivial_casts",
	"-Wtrivial_numeric_casts",
	"-Wunreachable_pub",
	"-Wunsafe_op_in_unsafe_fn",
	"-Wunstable_features",
	"-Wunused_import_braces",
	"-Wunused_lifetimes",
	"-Wunused_qualifications",
	"-Wunused_results",
	"-Wvariant_size_differences",
	# Temporary.
	"-Aclippy::missing_docs_in_private_items",
	"-Amissing_docs",
]
